[tool.poetry]
name = "04-airflow"
version = "0.1.0"
description = ""
authors = ["yes"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.8"
scikit-learn = "1.3.2"
matplotlib = "3.7.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
